# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sorusor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(452, 226)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 20, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.sorutext = QtWidgets.QPlainTextEdit(Form)
        self.sorutext.setGeometry(QtCore.QRect(30, 60, 401, 81))
        self.sorutext.setObjectName("sorutext")
        self.sorbuton = QtWidgets.QPushButton(Form)
        self.sorbuton.setGeometry(QtCore.QRect(180, 170, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sorbuton.setFont(font)
        self.sorbuton.setObjectName("sorbuton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Soru Sor"))
        self.label.setText(_translate("Form", "Matematik Dersi"))
        self.sorbuton.setText(_translate("Form", "Sor"))
