# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yanitver.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(475, 409)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 180, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tablo = QtWidgets.QTableWidget(self.centralwidget)
        self.tablo.setGeometry(QtCore.QRect(0, 0, 471, 161))
        self.tablo.setObjectName("tablo")
        self.tablo.setColumnCount(2)
        self.tablo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(1, item)
        self.yanitText = QtWidgets.QTextEdit(self.centralwidget)
        self.yanitText.setGeometry(QtCore.QRect(30, 220, 421, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.yanitText.setFont(font)
        self.yanitText.setObjectName("yanitText")
        self.yorumYapButon = QtWidgets.QPushButton(self.centralwidget)
        self.yorumYapButon.setGeometry(QtCore.QRect(170, 310, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.yorumYapButon.setFont(font)
        self.yorumYapButon.setObjectName("yorumYapButon")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 475, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Öğretmen"))
        self.label.setText(_translate("MainWindow", "Yanıt:"))
        item = self.tablo.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Öğrenci"))
        item = self.tablo.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Soru"))
        self.yorumYapButon.setText(_translate("MainWindow", "Yanıt Ver"))
